In [6]:
import numpy as np

# matrix
A = np.array([(1,2,3),(4,5,6)])
print(A)

[[1 2 3]
 [4 5 6]]


In [7]:
# vector(a special example of matrix)
v = np.array([7,8,9])
print(v)

[7 8 9]


In [8]:
# shape of matrix
m,n = A.shape
print(m,'x',n)

2 x 3


In [10]:
# index row 2 column 3 element of A
# 0-based
A_23 = A[1,2] 
print(A_23)

6
