In [2]:
import numpy as np
A=np.array([(1,2),(4,5)])
B=np.array([(1,1),(0,2)])
print(A)
print(B)

[[1 2]
 [4 5]]
[[1 1]
 [0 2]]


In [4]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [7]:
IA = I.dot(A)
print(IA)

[[1. 2.]
 [4. 5.]]


In [9]:
AI = A.dot(I)
print(AI)

[[1. 2.]
 [4. 5.]]


In [11]:
AB = A.dot(B)
print(AB)

[[ 1  5]
 [ 4 14]]


In [12]:
BA = B.dot(A)
print(BA)

[[ 5  7]
 [ 8 10]]
