In [5]:
import numpy as np
# initialize matrix A and B
A = np.array([(1,2,4),(5,3,2)])
B = np.array([(1,3,4),(1,1,1)])
print('A:\n',A)
print('B:\n',B)

A:
 [[1 2 4]
 [5 3 2]]
B:
 [[1 3 4]
 [1 1 1]]


In [7]:
# initialize constant s
s = 2

# see how element-wise addition works
add_AB = A+B
print(add_AB)

[[2 5 8]
 [6 4 3]]


In [9]:
# see how element-wise subtraction works
sub_AB = A-B
print(sub_AB)

[[ 0 -1  0]
 [ 4  2  1]]


In [11]:
# see how element-wise multiplication works
mult_As = A*s
print(mult_As)

[[ 2  4  8]
 [10  6  4]]


In [13]:
# divide A by s
div_As = A/s
print(div_As)

[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


In [14]:
# what happens if we have a matrix + scalar
add_As = A+s
print(add_As) # each element will add scalar


[[3 4 6]
 [7 5 4]]
