In [2]:
import numpy as np
A = np.array([(1,2,0),(0,5,6),(7,0,9)])
print(A)

[[1 2 0]
 [0 5 6]
 [7 0 9]]


In [4]:
A_trans = A.transpose()
print(A_trans)

[[1 0 7]
 [2 5 0]
 [0 6 9]]


In [10]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]


In [12]:
A_invA = A_inv.dot(A)
print(A_invA)


[[ 1.00000000e+00 -8.32667268e-17  5.55111512e-17]
 [-2.77555756e-17  1.00000000e+00 -2.77555756e-17]
 [-3.46944695e-17  2.77555756e-17  1.00000000e+00]]
