In [2]:
# initialize matrix A
import numpy as np
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# initialize vector v
v = np.array([1,1,1])
print(v)

[1 1 1]


multiply A * v

In [19]:
Av = A.dot(v)
print(Av)

[ 6 15 24]
